#dummy secret definition file you need to add values in data section.

apiVersion: v1
kind: Secret
metadata:
  name: backend-auth
data:
  DATABASE_URL: add database url here
  EMAIL: add email here
  EMAIL_PASS: add password here
